Allow library to be used by apps directly
Change-Id: Ib74be626471d73817d644c7777a2b18a32712f8a

Author: Adrian DC <radian.dc@gmail.com>
Date:   Thu Mar 8 22:46:55 2018 +0100
fm: Resolve required dependency qcom.fmradio.xml linkage

 * LOCAL_REQUIRED_MODULES should be used instead of
    LOCAL_ADDITIONAL_DEPENDENCIES to link a module

 * fm/Android.mk:
    error: qcom.fmradio: LOCAL_ADDITIONAL_DEPENDENCIES
    must only contain paths (not module names)

Change-Id: Ic0bebf752101f5d16abc52e085bae4acd0b0c61c